# Generated by Django 5.0.6 on 2024-06-22 17:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breweries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brewery',
            old_name='website',
            new_name='website_url',
        ),
        migrations.RemoveField(
            model_name='brewery',
            name='address',
        ),
        migrations.RemoveField(
            model_name='brewery',
            name='type',
        ),
        migrations.AddField(
            model_name='brewery',
            name='street',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brewery',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='state',
            field=models.CharField(max_length=255),
        ),
    ]
