# Generated by Django 5.0.6 on 2024-06-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breweries', '0002_rename_website_brewery_website_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brewery',
            name='street',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
